travis:
  secure:
    BINSTAR_TOKEN: o9meRGVPDLbZyddcY9J5QNtwFBUrjBPf3MqLlwhpiquRzYPQ/OYI/2UcNe40RDOrb9K7ZpQYMZYdZ5eFFQXfaah8QMLcud3dP+w+zm6Z8XVZWq9CJwNEuEOJo6aVqKaNq6tZYEOSwSbb2g3WWp2BLv/yon39wqa5VJGovsOjKV7zfLZdeR35XfLTE3I+OEeGHpek7NzxOdq4RAjVHKjVCJnA5PlcJbG4Q+8XYXx1/KcPyUy1v4jd35Dsirn9cwUfElcDTtyaAI23+K2Aak8vYu1AxkK4VeQKwpmNui9+/YRmbOvdveFAHJbgAcuap0xQ1FJroobXMa6r61ycWtDx242rpjiqxeOBPnQlcxBxM7y8DRKoy6j1w9qpfC8DeOi+FXTWniVFPu14IiuOMVtcP6GX5EpI1mzE/mbxQJFrbQ0oxouFBszUbRMUxYvJbQ+FuGJ3bG6H0pXHinh+lv9zuNucpkCQ2pr71aKtcO5uUQTBHAyn6WRjBBIEvtQ87K4ZDaBmBRWvDlJtiU73fMDCKz4dDuPZ7pL9wGioq2FQaLo9aJ9LCknXB9l1JbytFO7zU0Mzy7boEIeTazrdjSA0MWix2g9qtVjPysoKMX6yVRH77eSSZDq3QVrY/aQpbjHsu6NQ9Hsxvwq9oOzPh6tFBM372MKnR4VLguKo4OV1m6g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
